export type { DamageEvent, DamageResult, DamageKind } from './DamageEvent'
export { IFrameController } from './IFrameController'
export type { KnockbackRequest, KnockbackVector } from './Knockback'
export type { Hitbox, HitboxShape, OriginHitboxShape, HurtboxTarget } from './Hitbox'
export { hitboxOverlaps, resolveHurtbox } from './Hitbox'
export type { Hurtbox } from './Hurtbox'
export type { Combatant } from './Combatant'
export { CombatantRegistry } from './Combatant'
export { HitResolver } from './HitResolver'
