// Smoke 41-profiles (prompt 05 5.6, EVAL-P5-008): slot picker, name entry, first-run controls page once per
// profile, `{hero}` and the HUD label from the pilot name, CONTINUE into the same slot, export, clear, import.
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { chromium } from 'playwright'

export async function runProfilesScenario(name, { outputDir, storyUrl, readState, waitForState, advanceFrames, tapKey }) {
  const dir = path.join(outputDir, name)
  fs.rmSync(dir, { recursive: true, force: true })
  fs.mkdirSync(dir, { recursive: true })
  const browser = await chromium.launch({ headless: true, args: ['--use-gl=angle', '--use-angle=swiftshader'] })
  const context = await browser.newContext({ viewport: { width: 448, height: 252 }, acceptDownloads: true })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', (error) => errors.push(String(error)))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  const capture = async (label) => {
    await page.locator('canvas').screenshot({ path: path.join(dir, `shot-${label}.png`) })
    fs.writeFileSync(path.join(dir, `state-${label}.json`), JSON.stringify(await readState(page), null, 2))
  }
  const profileUrl = `${storyUrl}&profiles=on`
  const titleLabel = () => page.evaluate(() => window.__phaserGame.scene.getScene('Title').children.getByName('title-primary')?.text ?? null)
  try {
    await page.goto(profileUrl)
    await waitForState(page, (state) => state.scene === 'Title')
    await tapKey(page, 'Enter')
    const picker = await waitForState(page, (state) => state.scene === 'Profiles' && state.profiles?.screen?.mode === 'slots')
    assert.deepEqual(picker.profiles.slots.map((card) => card.pilotName), ['EMPTY', 'EMPTY', 'EMPTY'])
    await tapKey(page, 'ArrowRight')
    await waitForState(page, (state) => state.profiles?.screen?.slot === 2)
    await capture('1-slot-picker')
    await tapKey(page, 'Enter')
    const entry = await waitForState(page, (state) => state.profiles?.screen?.mode === 'name')
    assert.equal(entry.profiles.screen.name, 'WREN', 'the name defaults to WREN')
    for (const key of ['a', 'v', 'a']) await tapKey(page, key)
    await waitForState(page, (state) => state.profiles?.screen?.name === 'AVA')
    await capture('2-name-entry')
    await tapKey(page, 'Enter')
    const campaign = await waitForState(page, (state) => state.scene === 'NewCampaign')
    assert.deepEqual(campaign.profiles.pending, { slot: 2, pilotName: 'AVA' })
    await advanceFrames(page, 3)
    await tapKey(page, 'Enter')
    const firstRun = await waitForState(page, (state) => state.scene === 'Controls')
    assert.equal(await page.evaluate(() => window.__phaserGame.scene.getScene('Controls').firstRun), true, 'a new profile sees the first-run controls page')
    assert.equal(firstRun.profiles.activeSlot, 2)
    assert.deepEqual(firstRun.profiles.active, { pilotName: 'AVA', campaignStarted: true, controlsSeen: false })
    await capture('3-first-run-controls')
    await tapKey(page, 'Enter')
    const prologue = await waitForState(page, (state) => state.scene === 'Prologue' && state.prologue?.pageCount > 0)
    assert.equal(prologue.profiles.active.controlsSeen, true)
    await page.evaluate(() => window.narrativeDebug?.skip?.())
    const briefing = await waitForState(page, (state) => state.scene === 'Game' && state.stageIntro?.phase === 'briefing' && state.dialogue?.active === true, 10000)
    assert.equal(briefing.dialogue.sequenceId, 'tutorial_sentinel_briefing')
    assert.match(briefing.dialogue.text, /\bAVA\b/, 'the briefing line names the pilot')
    await capture('4-briefing-names-pilot')
    await page.evaluate(() => window.stageDebug?.skipDialogue?.())
    const control = await waitForState(page, (state) => state.stageIntro?.phase === 'done' && state.newPlayer?.locomotion?.grounded === true, 8000)
    assert.equal(control.identity.heroLabel, 'AVA', 'the HUD label follows the pilot')
    await page.evaluate(() => window.stageDebug.crossNextCheckpoint())
    const checkpoint = await waitForState(page, (state) => (state.stageRuntime?.checkpointIndex ?? 0) >= 1, 8000)
    await capture('5-first-checkpoint')
    // Quit (reload) and continue from Title into the same slot: no first-run page the second time.
    await page.goto(profileUrl)
    const title = await waitForState(page, (state) => state.scene === 'Title')
    assert.equal(title.profiles.activeSlot, 2)
    assert.match(await titleLabel(), /^CONTINUE/)
    await capture('6-title-continue')
    await tapKey(page, 'Enter')
    const second = await waitForState(page, (state) => state.scene === 'Game' && state.newPlayer?.locomotion?.grounded === true, 20000)
    assert.ok(!second.activeScenes.includes('Controls'), 'the first-run page does not show on the second entry')
    assert.equal(second.stageRuntime.stageId, 'tutorial_sentinel')
    assert.equal(second.identity.heroLabel, 'AVA')
    const renamed = await page.evaluate(() => window.stageDebug.setProfile({ slot: 2, pilotName: 'ava' }))
    assert.equal(renamed.ok, true)
    assert.equal(renamed.profiles.active.pilotName, 'AVA')
    await capture('7-second-entry')
    // Export from the slot picker, clear storage, import into the empty slot: the slot returns.
    await page.goto(profileUrl)
    await waitForState(page, (state) => state.scene === 'Title')
    await tapKey(page, 'n')
    await waitForState(page, (state) => state.scene === 'Profiles' && state.profiles?.screen?.slot === 2)
    const [download] = await Promise.all([page.waitForEvent('download'), tapKey(page, 'e')])
    assert.equal(download.suggestedFilename(), 'omega-relay-ava.json')
    const exportPath = path.join(dir, 'omega-relay-ava.json')
    await download.saveAs(exportPath)
    const exported = JSON.parse(fs.readFileSync(exportPath, 'utf8'))
    assert.equal(exported.kind, 'omega-relay-profile')
    assert.equal(exported.profile.pilotName, 'AVA')
    await capture('8-exported')
    await page.evaluate(() => localStorage.clear())
    await page.goto(profileUrl)
    const cleared = await waitForState(page, (state) => state.scene === 'Title')
    assert.equal(cleared.profiles.slots[1].empty, true)
    await tapKey(page, 'Enter')
    await waitForState(page, (state) => state.scene === 'Profiles')
    await tapKey(page, 'ArrowRight')
    await waitForState(page, (state) => state.profiles?.screen?.slot === 2)
    const [chooser] = await Promise.all([page.waitForEvent('filechooser'), tapKey(page, 'i')])
    await chooser.setFiles(exportPath)
    const restored = await waitForState(page, (state) => state.profiles?.slots?.[1]?.pilotName === 'AVA')
    assert.equal(restored.profiles.activeSlot, 2)
    assert.equal(restored.profiles.active.campaignStarted, true)
    assert.match(restored.profiles.screen.status, /IMPORTED AVA INTO SLOT 2/)
    await capture('9-imported')
    assert.deepEqual(errors, [])
    return { checkpointIndex: checkpoint.stageRuntime.checkpointIndex, briefingLine: briefing.dialogue.text, restored: restored.profiles.slots[1] }
  } finally {
    await browser.close()
  }
}
