// Builds src/content/credits.generated.ts from the attribution files so the in-game credits
// never drift from what ships. Run with `npm run credits:build`; a test asserts the file is in sync.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
export const OUTPUT_PATH = path.join(root, 'src/content/credits.generated.ts')
const AUDIO_README = path.join(root, 'assets/audio/credits/README.md')
const BACKGROUNDS_README = path.join(root, 'assets/backgrounds/README.md')
const SPRITE_ATTRIBUTION = path.join(root, 'assets/sprites/source/free-source-attribution.v1.json')

function field(block, name) {
  const match = block.match(new RegExp(`- ${name}: \`([^\`]+)\``))
  return match ? match[1] : null
}

/** Splits a markdown list into top-level entries that start with "- Track:" / "- Source pack:" / "- Title:". */
function entries(markdown, starters) {
  const lines = markdown.split('\n')
  const blocks = []
  let current = null
  for (const line of lines) {
    if (starters.some((starter) => line.startsWith(`- ${starter}:`)) || /^- `[^`]+`$/.test(line)) {
      if (current) blocks.push(current.join('\n'))
      current = [line]
    } else if (current) {
      current.push(line)
    }
  }
  if (current) blocks.push(current.join('\n'))
  return blocks
}

export function buildCredits({ audio, backgrounds, sprites }) {
  const lines = []
  for (const block of entries(audio, ['Track', 'Source pack'])) {
    const track = field(block, 'Track')
    const pack = field(block, 'Source pack')
    const author = field(block, 'Author')
    const license = field(block, 'License')
    if (track && author) lines.push(`Music: ${track} by ${author}${license ? ` (${license})` : ''}`)
    else if (pack && author) lines.push(`Sound: ${pack} by ${author}${license ? ` (${license})` : ''}`)
  }
  for (const block of entries(backgrounds, ['Title'])) {
    const title = field(block, 'Title')
    const author = field(block, 'Author')
    const license = field(block, 'License')
    if (title && author) lines.push(`Backgrounds: ${title} by ${author}${license ? ` (${license})` : ''}`)
  }
  const seen = new Set()
  for (const entry of sprites.entries ?? []) {
    const text = String(entry.attribution ?? '').replace(/\s+/g, ' ').trim()
    if (!text || seen.has(text)) continue
    seen.add(text)
    lines.push(`Art: ${text}${entry.license ? ` (${entry.license})` : ''}`)
  }
  return [...new Set(lines)]
}

export function readSources() {
  return {
    audio: fs.readFileSync(AUDIO_README, 'utf8'),
    backgrounds: fs.readFileSync(BACKGROUNDS_README, 'utf8'),
    sprites: JSON.parse(fs.readFileSync(SPRITE_ATTRIBUTION, 'utf8'))
  }
}

export function renderModule(lines) {
  const body = lines.map((line) => `  ${JSON.stringify(line)}`).join(',\n')
  return `// Generated by scripts/credits/build-credits.mjs from the attribution files. Do not edit; run \`npm run credits:build\`.\nexport const ASSET_CREDITS: readonly string[] = [\n${body}\n]\n`
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const lines = buildCredits(readSources())
  fs.writeFileSync(OUTPUT_PATH, renderModule(lines))
  console.log(`Wrote ${path.relative(root, OUTPUT_PATH)} (${lines.length} credit lines).`)
}
